name: Compat Check w/PL - latest/latest

on:
  schedule:
    - cron: "0 3 * * 1-5"  # Run daily at 3am Mon-Fri
  workflow_dispatch:

jobs:
  tests_linux_x86:
    name: Lightning-GPU Compatibility test (tests_linux_x86) - latest/latest
    uses: ./.github/workflows/tests_linux_x86.yml
    with:
      lightning-gpu-version: latest
      pennylane-version: latest

  tests_linux_x86_mpich:
    name: Lightning-GPU Compatibility test (tests_linux_x86_mpich) - latest/latest
    uses: ./.github/workflows/tests_linux_x86_mpich.yml
    with:
      lightning-gpu-version: latest
      pennylane-version: latest

