name: Tests::Linux::x86_64
on:
  release:
  push:
    branches:
      - main
  pull_request:

env:
  COVERAGE_FLAGS: "--cov=pennylane_lightning_gpu --cov-report=term-missing --cov-report=xml:./coverage.xml --no-flaky-report -p no:warnings --tb=native" 
  GCC_VERSION: 11
  OMP_NUM_THREADS: "2"
  CI_CUDA_ARCH: 86

concurrency:
  group: gpu-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cpptests:
    runs-on:
      - self-hosted
      - ubuntu-22.04
      - gpu

    strategy:
      max-parallel: 1

    steps:
      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.8'

      - name: Remove Ubuntu unattended upgrades
        run: sudo apt-get remove -y -q unattended-upgrades

      - name: Install required packages
        run: |
          sudo apt-get update && sudo apt-get -y -q install gcc-${{ env.GCC_VERSION }} g++-${{ env.GCC_VERSION }} gcovr lcov
          python -m pip install ninja cmake~=3.24.3 cuquantum

      - name: Checkout pennyLane-lightning-gpu
        uses: actions/checkout@v3

      - name: Validate GPU version and installed compiler
        run: |
          nvidia-smi
          /usr/local/cuda/bin/nvcc --version

      - name: Build and run unit tests
        run: |
            cmake . -BBuild \
              -DCMAKE_BUILD_TYPE=RelWithDebInfo \
              -DPLLGPU_BUILD_TESTS=ON \
              -DCMAKE_CXX_COMPILER="$(which g++-${{ env.GCC_VERSION }})" \
              -DLIGHTNING_RELEASE_TAG="master" \
              -DCMAKE_CUDA_COMPILER="/usr/local/cuda/bin/nvcc" \
              -DCMAKE_CUDA_ARCHITECTURES="86" \
              -G Ninja
            cmake --build ./Build
            cd ./Build
            mkdir -p ./tests/results
            ./pennylane_lightning_gpu/src/tests/runner_gpu --order lex --reporter junit --out ./tests/results/report_${{ github.job }}.xml

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ubuntu-tests-reports
          path: ./Build/tests/results/report_${{ github.job }}.xml

      - name: Build and run unit tests for code coverage
        run: |
            cmake . -BBuildCov \
              -DCMAKE_BUILD_TYPE=Debug \
              -DPLLGPU_BUILD_TESTS=ON \
              -DPLLGPU_ENABLE_COVERAGE=ON \
              -DCMAKE_CXX_COMPILER="$(which g++-${{ env.GCC_VERSION }})" \
              -DLIGHTNING_RELEASE_TAG="master" \
              -DCMAKE_CUDA_COMPILER="/usr/local/cuda/bin/nvcc" \
              -DCMAKE_CUDA_ARCHITECTURES="86" \
              -G Ninja
            cmake --build ./BuildCov
            cd ./BuildCov
            ./pennylane_lightning_gpu/src/tests/runner_gpu
            lcov --directory . -b ../pennylane_lightning_gpu/src --capture --output-file coverage.info
            lcov --remove coverage.info '/usr/*' --output-file coverage.info
            mv coverage.info coverage-${{ github.job }}.info

      - name: Upload code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-codecov-results-cpp
          path: ./BuildCov/coverage-${{ github.job }}.info

      - name: Cleanup
        if: always()
        run: |
          rm -rf *
          rm -rf .git
          rm -rf .gitignore
          rm -rf .github


  pythontests:
    runs-on:
      - self-hosted
      - ubuntu-22.04
      - gpu

    strategy:
      max-parallel: 1

    steps:
      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.8'

      - name: Install required packages
        run: |
          python -m pip install ninja cmake~=3.24.3 cuquantum pytest pytest-mock flaky pytest-cov
          sudo apt-get update && sudo apt-get -y -q install gcc-${{ env.GCC_VERSION }} g++-${{ env.GCC_VERSION }} gcovr lcov
          # Sync with latest master branches
          python -m pip install git+https://github.com/PennyLaneAI/pennylane.git@v0.29.0-rc0
          python -m pip install --index-url https://test.pypi.org/simple/ pennylane-lightning --pre
          
      - name: Checkout pennyLane-lightning-gpu
        uses: actions/checkout@v3

      - name: Build and install package
        run: |
            python setup.py build_ext -i --define="CMAKE_CXX_COMPILER=$(which g++-${{ env.GCC_VERSION }});LIGHTNING_RELEASE_TAG=v0.29.0_rc0;CMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc;CMAKE_CUDA_ARCHITECTURES=${{ env.CI_CUDA_ARCH }}"
            python -m pip install -e .

      - name: Run PennyLane-Lightning-GPU unit tests
        run: |
          pytest ./tests/ ${{ env.COVERAGE_FLAGS }}
          pl-device-test --device lightning.gpu --skip-ops --shots=20000 ${{ env.COVERAGE_FLAGS }} --cov-append
          pl-device-test --device lightning.gpu --shots=None --skip-ops ${{ env.COVERAGE_FLAGS }} --cov-append
          mv coverage.xml coverage-${{ github.job }}.xml

      - name: Upload code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-codecov-results-python
          path: ./coverage-${{ github.job }}.xml

      - name: Cleanup
        if: always()
        run: |
          rm -rf *
          rm -rf .git
          rm -rf .gitignore
          rm -rf .github
